
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://mnapier.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /mnapier.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-79508162-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Mark Napier"
title: "{ Mark Napier }"
description: "Blog and website of Mark Napier, blogging mainly for tech. Opinions expressed are mine."
keywords: "napier, mark, personal, jekyll"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "TODO"
  - text: "FIXME"

me-img: "/img/me.png"

##############################
# Color the browser elements #
##############################
color-browser: "#393D3F"
apple-status-bar-style: "393D3F"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "mnapier"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/kycot.jpg"
    date: "February 2016 - Today"
    description: "Senior Java Developer @ <a href='http://technology.ky.gov/' target='_blank'>Kentucky Commonwealth Office of Technology</a>"
  - image: "/img/timeline/savi.jpg"
    date: "August 2012 - January 2016"
    description: "Software Engineer @ <a href='http://www.savi.com/' target='_blank'>Savi Technology, Inc</a>"
  - image: "/img/timeline/galmont.png"
    date: "March 2011 - August 2012"
    description: "Senior Software Tester @ <a href='http://www.galmont.com/' target='_blank'>Galmont Consulting, LLC</a>"
  - image: "/img/timeline/bestpcservice.jpg"
    date: "November 2010 - March 2011"
    description: "Independent Contractor @ <a href='http://www.bestpcsos.com/' target='_blank'>Best PC Service</a>"
  - image: "/img/timeline/coldwellbanker_deslooverrealty.jpg"
    date: "January 2010 - March 2011"
    description: "Web Developer @ <a href='http://www.coldwellbankerky.com' target='_blank'>Coldwell Banker DeSloover Realty</a>"
  - image: "/img/timeline/kygamers.jpg"
    date: "March 2006 - March 2008"
    description: "Web Developer @ KYGamers.com"
  - image: "/img/timeline/eku.jpg"
    date: "August 2005 - May 2010"
    description: "Computer Science Student @ <a href='http://www.eku.edu/' target='_blank'>Eastern Kentucky University</a>"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

#############
# Portfolio #
#############

portfolio-items:
  - image: "/img/portfolio/savi-tracking/Savi_ETAaaS_Screenshot_Shipments_Overview.png"
    title: "Savi Tracking"
    short_description: "Real-Time Visibility for In-Transit Assets"
    description: "Savi Tracking identifies and monitors the location and status of your assets in transit. You need to know where your high value assets are, when they will arrive, what condition they are in, and if they are secure. Specialized software and tamperproof hardware secure and monitor multiple cargo types to improve performance, reduce risk, and minimize supply chain disruptions."
    url: "http://www.savi.com/solutions/applications/savi-tracking/"
  - image: "/img/portfolio/reloaders-supply/reloaderssupply.com.png"
    title: "Reloader's Supply"
    short_description: "WooCommerce based eCommerce website"
    description: ""
    url: "http://www.reloaderssupply.com/"

###########
# Contact #
###########

email: "markwnapier@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Mark Napier is a full stack Software Engineer with over 9 years of development experience. He lives in Lexington, KY, where he works on engineering projects. In his spare time, Mark likes to build RC quadcopters and enhance his Shapeoko CNC machine."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/dutchovens"
  - title: "twitter"
    url: "https://twitter.com/dutchovens"
  - title: "github"
    url: "https://github.com/mnapier"
  # - title: "bitcoin"
    # url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Portfolio: 'portfolio'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
